/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Personaje;
import Modelo.*;
import Modelo.FabricaPersonaje;
import java.io.File;
import javax.imageio.ImageIO;

/**
 *
 * @author Estudiantes
 */
public class preJuego extends javax.swing.JFrame {

    JFVInicio v = new JFVInicio();
    private static Personaje INSTANCE = null;
    public String cabeza,cuerpo,piernas;
    Personaje[] clon;
    int slider = 1;

    public preJuego() {
        this.setVisible(true);
        getContentPane().add((new dibujarPre()));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sliderPjs = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jbr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/NumPj.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 290, 300, 100);

        sliderPjs.setBackground(new java.awt.Color(204, 204, 204));
        sliderPjs.setFont(new java.awt.Font("Zorque", 1, 11)); // NOI18N
        sliderPjs.setForeground(new java.awt.Color(255, 0, 0));
        sliderPjs.setMajorTickSpacing(1);
        sliderPjs.setMaximum(10);
        sliderPjs.setMinimum(1);
        sliderPjs.setPaintLabels(true);
        sliderPjs.setPaintTicks(true);
        sliderPjs.setToolTipText("");
        sliderPjs.setValue(1);
        sliderPjs.setOpaque(false);
        sliderPjs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderPjsStateChanged(evt);
            }
        });
        getContentPane().add(sliderPjs);
        sliderPjs.setBounds(50, 400, 200, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Jugar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 390, 140, 60);

        jbr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Retroceder.png"))); // NOI18N
        jbr.setBorder(null);
        jbr.setBorderPainted(false);
        jbr.setContentAreaFilled(false);
        jbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrActionPerformed(evt);
            }
        });
        getContentPane().add(jbr);
        jbr.setBounds(130, 0, 240, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/wdas.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderPjsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderPjsStateChanged
        System.out.println("Clones deseados: " + sliderPjs.getValue());
        getContentPane().add(sliderPjs);
        int n=sliderPjs.getValue();
        setSlider(n);
    }//GEN-LAST:event_sliderPjsStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int n = getSlider();
        crearPjs(n);
        System.out.println(clon);
        AbrirVentanaJuego();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrActionPerformed
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();      
    }//GEN-LAST:event_jbrActionPerformed

    public int getSlider() {
        return slider;
    }

    public void setSlider(int slider) {
        this.slider = slider;
    }

    public void AbrirVentanaJuego() {
        VentanaJuego v = new VentanaJuego(slider);
        v.setVisible(true);
        v.setLocationRelativeTo(null);
    }

    public void crearPjs(int num) {
        JFVInicio j = new JFVInicio();
        Personaje pj = null;
        String creacion = j.getVentana();
        if (creacion == "humano") {
            pj = getPersonaje(new FabricaHumano());
        }
        if (creacion == "hibrido") {
            pj = getPersonaje(new FabricaHibrido());
        }
        if (creacion == "alien") {
            pj = getPersonaje(new FabricaAlien());
        }
        clon = new Personaje[num];
        clon[0] = pj;
        clonarPjs(num, pj);
    }

    public Personaje[] clonarPjs(int numero, Personaje pj) {
        int i;
        for (i = 1; i < numero; i++) {
            clon[i] = pj.Clonar();
        }
        return clon;
    }

    public Personaje[] getClon() {
        return clon;
    }

    public static synchronized Personaje getPersonaje(FabricaPersonaje factory) {
        if (INSTANCE == null) {
            Personaje pj = factory.crearPersonaje();
            pj.getCasco();
            pj.getArmadura();
            pj.getBotas();
            INSTANCE = pj;
        }
        return INSTANCE;
    }

    public static void setPersonaje(Personaje INSTANCE) {
        preJuego.INSTANCE = INSTANCE;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbr;
    private javax.swing.JSlider sliderPjs;
    // End of variables declaration//GEN-END:variables
}
